Fit_worldz/core/views.py
from flask import render_template,request,Blueprint


core = Blueprint('core',__name__)

@core.route('/')
def index():
    '''
    This is the home page view. Notice how it uses pagination to show a limited
    number of posts by limiting its query size and then calling paginate.
    '''

    return render_template('index.html')

@core.route('/info')
def info():
    '''
    Example view of any other "core" page. Such as a info page, about page,
    contact page. Any page that doesn't really sync with one of the models.
    '''
    return render_template('info.html')

Fit_worldz/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="jumbotron">
    <div align='center'>
        <h1> Welcome to the Account page fr {{ current_user.username }} </h1>
        <img align="center" src="{{ url_for('static',filename='profile_pics/'+current_user.profile_image)}}">

    </div>

########### form with bootstrap classes for example####################
</div>

    <div class="container">
    <form method="POST">
 {{ form.hidden_tag() }}
        <div class="form-group">

    {{ form.username.label(class="form-group") }}  {{ form.username }}
    {{ form.username(class='form-control') }}
        </div>



 <div class="form-group">
    {{ form.email.label(class="form-group") }}  {{ form.email }}
     {{ form.email(class='form-control') }}

        </div>

 <div class="form-group">
        {{ form.picture.label(class="form-group") }}  {{ form.picture }}
     {{ form.picture(class='form-control') }}

        </div>

 <div class="form-group">
        {{ form.submit(class='btn btn-primary') }}
 </div>

    </form>

    </div>

{% endblock %}

Fit_worldz/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <meta charset="utf-8">
    <title></title>
  </head>
  <body>

    <ul class='nav'>
      <li class='nav-link'>
        <a href="{{url_for('core.index')}}">Home</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">About</a>
      </li>

      <li class='nav-link'>
        <a href="#">Log Out</a>
      </li>
      <li class='nav-link'>
        <a href="#">Account</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">Add Workout</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">View Workouts</a>
      </li>
      <li class='nav-link'>
        <a href="{{url_for('core.info')}}">Add Excercise</a>
      </li>
      <li class='nav-link'>
        <a href="#">Create Post</a>
      </li>

      <li class='nav-link'>
        <a href="#">Log In</a>
      </li>
      <li class='nav-link'>
        <a href="#">Register</a>
      </li>
    </ul>
<div class="container">
  {% block content %}

  {% endblock %}
</div>


  </body>
</html>

Fit_worldz/templates/index.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Welcome to Fit World</h1>
  </div>
{% endblock %}

Fit_worldz/templates/info.html
{% extends "base.html" %}
{% block content %}
  <div class="jumbotron">
    <h1>Info about our company</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  </div>
{% endblock %}

Fit_worldz/templates/login.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }}  {{ form.email }} <br>
        {{ form.password.label }}  {{ form.password }} <br>
         }}
        {{ form.submit() }}

    </form>
{% endblock %}

Fit_worldz/templates/register.html
{% extends "base.html" %}
{% block content %}
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label }}  {{ form.email }} <br>
        {{ form.username.label }}  {{ form.username }} <br>
        {{ form.password.label }}  {{ form.password }} <br>
        {{ form.pass_confirm.label }}  {{ form.pass_confirm }} <br>
        {{ form.submit() }}

    </form>
{% endblock %}

Fit_worldz/templates/user_posts.html
{% extends 'base.html' %}

{% block content %}
<div class="jumbotron">
<div align="center">
    <h1> Welcome to the page for {{ user.username }}</h1>
    <img src="{{ url_for('static' }}"


</div>


</div>


{% endblock %}